# Generated by Django 4.2.3 on 2023-07-12 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committees',
            name='convener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committees',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committees',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
