# Generated by Django 4.2.3 on 2023-07-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_committees_convener_alter_committees_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODnotices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=2000)),
            ],
        ),
    ]
