# Generated by Django 4.2.3 on 2023-09-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_notices_delete_hodnotices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent_directory',
            field=models.CharField(default='C:\\Users\\uditi\\OneDrive\\Desktop\\College stuff\\Internship Stuff\\In-house\\internship_1307\\media\\files/', max_length=10000, unique=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
