# Generated by Django 4.2.2 on 2023-09-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_folder_parent_directory_alter_userlist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
