# Generated by Django 4.2.3 on 2023-09-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_userlist_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notices',
        ),
    ]
