# Generated by Django 5.0 on 2023-12-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_notices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=20000, upload_to='cat/'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_directory',
            field=models.CharField(default='C:\\Users\\uditi\\OneDrive\\Desktop\\College stuff\\Internship Stuff\\In-house\\Internship\\media\\files/', max_length=10000, unique=True),
        ),
    ]
