# Generated by Django 5.0 on 2023-12-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_file_file_alter_folder_parent_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committees',
            name='convener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.userlist'),
        ),
        migrations.AlterField(
            model_name='committees',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='base.userlist'),
        ),
        migrations.AlterField(
            model_name='committees',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff', to='base.userlist'),
        ),
    ]
